### PR TITLE
CleanContent -> CleanString

### PR DESCRIPTION
**Pull request by plutov**

### CODE REVIEW

**Comment by bbalet** [comment]
This would break the API... What is the point?

**Comment by plutov** [comment]
I just found that function in stopwords.go has name CleanString, but in README and tests it has another name.

**Comment by bbalet** [comment]
OK, I will check that on my desktop.

Le 5 août 2016 06:34, "Aliaksandr Pliutau" <notifications@github.com> a
écrit :

**Comment by bbalet** [comment]
Thank you.

**Pull request merged**
